### ISSUE TITLE
[share] RN 기술 공유

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami-app#2]
### React Native 환경세팅 자료
- https://reactnative.dev/docs/typescript
- https://reactnative.dev/

### webview 세팅 및 RN <-> webview 통신
- [webview 세팅 및 RN <--> webview 통신](https://kyounghwan01.github.io/blog/React/react-native/react-native-webview/#%E1%84%8B%E1%85%B0%E1%86%B8%E1%84%87%E1%85%B2%E1%84%8B%E1%85%A6%E1%84%89%E1%85%A5-rn%E1%84%8B%E1%85%B3%E1%84%85%E1%85%A9-%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5-%E1%84%89%E1%85%A9%E1%86%BC%E1%84%89%E1%85%B5%E1%86%AB)
- [React native 와 WebView 데이터 통신](https://bangc.tistory.com/8)
- https://kyounghwan01.github.io/blog/React/react-native/react-native-webview/#rn-%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%8C%E1%85%A6%E1%86%A8%E1%84%90%E1%85%B3-%E1%84%86%E1%85%B5%E1%86%BE-%E1%84%8B%E1%85%B0%E1%86%B8-%E1%84%87%E1%85%B2-%E1%84%85%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%87%E1%85%B3%E1%84%85%E1%85%A5%E1%84%85%E1%85%B5-%E1%84%89%E1%85%A5%E1%86%AF%E1%84%8E%E1%85%B5
- https://talkwithcode.tistory.com/18

### UUID 발급 받기
- [RN UUID](https://devbksheen.tistory.com/entry/UUID-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EC%82%AC%EC%9A%A9)
- [react-native-uuid npm](https://www.npmjs.com/package/react-native-uuid)

### weview에서 현위치 가져오기 허용
- [사용자 현재 위치 가져오기 + 현재위치 사용 허락 요청](https://velog.io/@tjdgus0528/React-Native-%EC%82%AC%EC%9A%A9%EC%9E%90-%ED%98%84%EC%9E%AC-%EC%9C%84%EC%B9%98-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0-%ED%98%84%EC%9E%AC%EC%9C%84%EC%B9%98-%EC%82%AC%EC%9A%A9-%ED%97%88%EB%9D%BD-%EC%9A%94%EC%B2%AD)

### webview 공부 내용
`onLoadStart`: webview 시작할 때 실행
`onLoad` : webview 끝날 때 실행
 

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by thdwlsgus0** [comment]
rn이 아니라서 이 이슈는 닫도록 할게요~
