### ISSUE TITLE
[app] android 로고 이슈 

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami-app#38]
### 이슈
- `android` 로고 이슈 발생

### 체크리스트
- [ ] 발생하는 이유 파악
- [ ] 로고 색상 변경

**Comment by thdwlsgus0** [comment]
@kingyong9169 이거 혹시 실기기에서 됐나요?

**Comment by kingyong9169** [comment]
> @kingyong9169 이거 혹시 실기기에서 됐나요?

실기기 확인해보니 잘 나오네용 기기마다 다를 수도 있을 것 같아요ㅠ

<img src="https://user-images.githubusercontent.com/62797441/227764170-dd244a34-a1a2-46a3-8227-1ec5239dcf6f.jpg" width=400 />

<img src="https://user-images.githubusercontent.com/62797441/227764162-621449a4-261b-4689-9b44-ccfe14688682.jpg" width=400 />

**Comment by thdwlsgus0** [comment]
일단 잘 나오는 것 같아서 이슈 닫겠습니다~
