### ISSUE TITLE
[iOS] 캠퍼스맵 이슈

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami-app#44]
https://user-images.githubusercontent.com/62797441/26099465-f024b85b-eb0d-45ff-9f14-c90a967cf039.mov

@thdwlsgus0 iOS에서 캠퍼스맵을 클릭하면 화면이 멈춰서 나오지 않습니다. 오류 메시지도 안뜨구요..

**Comment by thdwlsgus0** [comment]
@kingyong9169 프론트 naver maps api 문제인 것 같아서 해당 pr올렸어요~ 참고 부탁드려요!

**Comment by thdwlsgus0** [comment]
@kingyong9169 

해당 이슈는 제 생각은 https에 관련된 이슈인 것 같아요
dev는 접속이 되고 local은 접속이 안되는 것 같은데 코드로 다른 부분은 없거든요.. `dev` 브랜치의 것이랑 비교를 했거든요
브루니 이슈 머지해보고 simulator랑 리얼 환경에서 테스트 다시 해보시죠

**Comment by kingyong9169** [comment]
@thdwlsgus0 넵 확인했습니다~ 제 PR 머지하고 리얼 환경에서 다시 테스트해볼게요!

테스트 전까지 이슈는 살려두겠습니다~

**Comment by thdwlsgus0** [comment]
@kingyong9169 리얼환경에서 정상적으로 노출되는 것 같은데 확인 부탁드립니다.

**Comment by kingyong9169** [comment]
> @kingyong9169 리얼환경에서 정상적으로 노출되는 것 같은데 확인 부탁드립니다.

넵 확인해보겠습니다~

**Comment by kingyong9169** [comment]
정상적으로 보여서 이슈는 닫겠습니다~!
